spring.application.name=bff-agendador
spring.config.import=optional:file:.env[.properties]
spring.cloud.openfeign.httpclient.hc5.enabled=true

usuario.url=${USUARIO_URL:http://localhost:8080/usuario}
agendador-tarefas.url=${AGENDADOR_TAREFAS_URL:http://localhost:8081/tarefas}
notificador.url=${NOTIFICADOR_URL:http://localhost:8082/email}

server.port=8083
cron.horario=${CRON_SCHEDULE:0 0/5 * * * ?}
usuario.email=${CRON_USER_EMAIL}
usuario.senha=${CRON_USER_PASSWORD}
